text_prompt_dict = {
    "cifar100": {
        "classes": [
            'apple',
            'aquarium fish',
            'baby',
            'bear',
            'beaver',
            'bed',
            'bee',
            'beetle',
            'bicycle',
            'bottle',
            'bowl',
            'boy',
            'bridge',
            'bus',
            'butterfly',
            'camel',
            'can',
            'castle',
            'caterpillar',
            'cattle',
            'chair',
            'chimpanzee',
            'clock',
            'cloud',
            'cockroach',
            'couch',
            'crab',
            'crocodile',
            'cup',
            'dinosaur',
            'dolphin',
            'elephant',
            'flatfish',
            'forest',
            'fox',
            'girl',
            'hamster',
            'house',
            'kangaroo',
            'keyboard',
            'lamp',
            'lawn mower',
            'leopard',
            'lion',
            'lizard',
            'lobster',
            'man',
            'maple tree',
            'motorcycle',
            'mountain',
            'mouse',
            'mushroom',
            'oak tree',
            'orange',
            'orchid',
            'otter',
            'palm tree',
            'pear',
            'pickup truck',
            'pine tree',
            'plain',
            'plate',
            'poppy',
            'porcupine',
            'possum',
            'rabbit',
            'raccoon',
            'ray',
            'road',
            'rocket',
            'rose',
            'sea',
            'seal',
            'shark',
            'shrew',
            'skunk',
            'skyscraper',
            'snail',
            'snake',
            'spider',
            'squirrel',
            'streetcar',
            'sunflower',
            'sweet pepper',
            'table',
            'tank',
            'telephone',
            'television',
            'tiger',
            'tractor',
            'train',
            'trout',
            'tulip',
            'turtle',
            'wardrobe',
            'whale',
            'willow tree',
            'wolf',
            'woman',
            'worm',
        ],
        "templates": [
            'a photo of a {}.',
            'a blurry photo of a {}.',
            'a black and white photo of a {}.',
            'a low contrast photo of a {}.',
            'a high contrast photo of a {}.',
            'a bad photo of a {}.',
            'a good photo of a {}.',
            'a photo of a small {}.',
            'a photo of a big {}.',
            'a photo of the {}.',
            'a blurry photo of the {}.',
            'a black and white photo of the {}.',
            'a low contrast photo of the {}.',
            'a high contrast photo of the {}.',
            'a bad photo of the {}.',
            'a good photo of the {}.',
            'a photo of the small {}.',
            'a photo of the big {}.',
        ]
    },
    "imagenet_r": {
        "classes": [
            'goldfish',
            'great white shark',
            'hammerhead shark',
            'stingray',
            'hen',
            'ostrich',
            'goldfinch',
            'junco',
            'bald eagle',
            'vulture',
            'smooth newt',
            'axolotl',
            'tree frog',
            'green iguana',
            'chameleon',
            'Indian cobra',
            'scorpion',
            'tarantula',
            'centipede',
            'peafowl',
            'lorikeet',
            'hummingbird',
            'toucan',
            'duck',
            'goose',
            'black swan',
            'koala',
            'jellyfish',
            'snail',
            'American lobster',
            'hermit crab',
            'flamingo',
            'great egret',
            'pelican',
            'king penguin',
            'grey whale',
            'killer whale',
            'sea lion',
            'Chihuahua',
            'Shih Tzu',
            'Afghan Hound',
            'Basset Hound',
            'Beagle',
            'Bloodhound',
            'Italian Greyhound',
            'Whippet',
            'Weimaraner',
            'Yorkshire Terrier',
            'Boston Terrier',
            'Scottish Terrier',
            'West Highland White Terrier',
            'Golden Retriever',
            'Labrador Retriever',
            'Cocker Spaniel',
            'collie',
            'Border Collie',
            'Rottweiler',
            'German Shepherd Dog',
            'Boxer',
            'French Bulldog',
            'St. Bernard',
            'Siberian Husky',
            'Dalmatian',
            'pug',
            'Pomeranian',
            'Chow Chow',
            'Pembroke Welsh Corgi',
            'Toy Poodle',
            'Standard Poodle',
            'grey wolf',
            'hyena',
            'red fox',
            'tabby cat',
            'leopard',
            'snow leopard',
            'lion',
            'tiger',
            'cheetah',
            'polar bear',
            'meerkat',
            'ladybug',
            'fly',
            'bee',
            'ant',
            'grasshopper',
            'cockroach',
            'praying mantis',
            'dragonfly',
            'monarch butterfly',
            'starfish',
            'cottontail rabbit',
            'porcupine',
            'fox squirrel',
            'beaver',
            'guinea pig',
            'zebra',
            'pig',
            'hippopotamus',
            'bison',
            'gazelle',
            'llama',
            'skunk',
            'badger',
            'orangutan',
            'gorilla',
            'chimpanzee',
            'gibbon',
            'baboon',
            'giant panda',
            'eel',
            'clownfish',
            'pufferfish',
            'accordion',
            'ambulance',
            'assault rifle',
            'backpack',
            'barn',
            'wheelbarrow',
            'basketball',
            'bathtub',
            'lighthouse',
            'beer glass',
            'binoculars',
            'birdhouse',
            'bow tie',
            'broom',
            'bucket',
            'cauldron',
            'candle',
            'cannon',
            'canoe',
            'carousel',
            'castle',
            'mobile phone',
            'cowboy hat',
            'electric guitar',
            'fire truck',
            'flute',
            'gas mask or respirator',
            'grand piano',
            'guillotine',
            'hammer',
            'harmonica',
            'harp',
            'hatchet',
            'jeep',
            'joystick',
            'lab coat',
            'lawn mower',
            'lipstick',
            'mailbox',
            'missile',
            'mitten',
            'parachute',
            'pickup truck',
            'pirate ship',
            'revolver',
            'rugby ball',
            'sandal',
            'saxophone',
            'school bus',
            'schooner',
            'shield',
            'soccer ball',
            'space shuttle',
            'spider web',
            'steam locomotive',
            'scarf',
            'submarine',
            'tank',
            'tennis ball',
            'tractor',
            'trombone',
            'vase',
            'violin',
            'military aircraft',
            'wine bottle',
            'ice cream',
            'bagel',
            'pretzel',
            'cheeseburger',
            'hot dog',
            'cabbage',
            'broccoli',
            'cucumber',
            'bell pepper',
            'mushroom',
            'Granny Smith apple',
            'strawberry',
            'lemon',
            'pineapple',
            'banana',
            'pomegranate',
            'pizza',
            'burrito',
            'espresso',
            'volcano',
            'baseball player',
            'scuba diver',
            'acorn',
        ],
        "templates": [
            'itap of a {}.',
            'a bad photo of the {}.',
            'a origami {}.',
            'a photo of the large {}.',
            'a {} in a video game.',
            'art of the {}.',
            'a photo of the small {}.',
        ],
    },
    "sdomainet": {
        "classes": [
            'pickup truck',
            'sweater',
            'The Eiffel Tower',
            'backpack',
            'waterslide',
            'lion',
            'submarine',
            'toothpaste',
            'banana',
            'television',
            'cruise ship',
            'lighthouse',
            'sandwich',
            'bee',
            'rhinoceros',
            'tornado',
            'golf club',
            'ladder',
            'tiger',
            'castle',
            'kangaroo',
            'frog',
            'pillow',
            'goatee',
            'horse',
            'circle',
            'toothbrush',
            'washing machine',
            'eye',
            'river',
            'basket',
            'spoon',
            'sea turtle',
            'bracelet',
            'coffee cup',
            'strawberry',
            'squirrel',
            'cat',
            'teapot',
            'mug',
            'elephant',
            'swan',
            'raccoon',
            'onion',
            'animal migration',
            'nail',
            'sock',
            'sword',
            'hedgehog',
            'donut',
            'crocodile',
            'ocean',
            'leg',
            'drums',
            'hand',
            'penguin',
            'speedboat',
            'zigzag',
            'pizza',
            'windmill',
            'square',
            'shovel',
            'guitar',
            'sheep',
            'suitcase',
            'flashlight',
            'steak',
            'duck',
            'sailboat',
            'triangle',
            'yoga',
            'broccoli',
            'beach',
            'fence',
            'binoculars',
            'garden',
            'shorts',
            'mushroom',
            'teddy-bear',
            'bicycle',
            'snowman',
            'see saw',
            'pineapple',
            'truck',
            'shoe',
            'nose',
            'hexagon',
            'squiggle',
            'umbrella',
            'ice cream',
            'candle',
            'grass',
            'necklace',
            'barn',
            'popsicle',
            'palm tree',
            'rabbit',
            'eyeglasses',
            'motorbike',
            'dog',
            'bus',
            'dumbbell',
            'pond',
            'whale',
            'cake',
            'wine bottle',
            'moon',
            'pig',
            'sleeping bag',
            'feather',
            'tent',
            'brain',
            'fish',
            'bird',
            'scorpion',
            'wine glass',
            'snorkel',
            'map',
            'stove',
            'school bus',
            'pear',
            'dolphin',
            'rollerskates',
            'moustache',
            'mountain',
            'stethoscope',
            'spider',
            'bottlecap',
            'bowtie',
            'octopus',
            'watermelon',
            'car',
            'toilet',
            'light bulb',
            'harp',
            'door',
            'asparagus',
            'tree',
            'table',
            'toaster',
            'tractor',
            'spreadsheet',
            'skateboard',
            'helmet',
            'beard',
            'monkey',
            'vase',
            'crab',
            'skyscraper',
            'snail',
            'train',
            'giraffe',
            'finger',
            'cup',
            'butterfly',
            'scissors',
            'zebra',
            'parachute',
            'stairs',
            'bench',
            'owl',
            'book',
            'rifle',
            'carrot',
            'trombone',
            'flower',
            'streetlight',
            'wristwatch',
            'snake',
            'pool',
            'saxophone',
            'grapes',
            'violin',
            'hamburger',
            'bread',
            'face',
            'bridge',
            'hat',
            'lobster',
            'shark',
            'headphones',
            'leaf',
            'house plant',
            'skull',
            'telephone',
            'envelope',
            'broom',
            'hot tub',
            'bed',
            'canoe',
            'firetruck',
            'bear',
            'sun',
            'syringe',
            'hot air balloon',
            'van',
            'helicopter',
            'flamingo',
            'blueberry',
            'parrot',
        ],
        "templates": [
            "a clipart of a {}",
            "a clipart of the {}",
            "a infograph of a {}",
            "a infograph of the {}",
            "a painting of a {}",
            "a painting of the {}",
            "a quickdraw of a {}",
            "a quickdraw of the {}",
            "a real photo of a {}",
            "a real photo of the {}",
            "a sketch of a {}",
            "a sketch of the {}",
        ]
    },
    'cub200': {
        'classes': [
            line.strip().split(' ', 1)[1].replace('_', ' ')  # 关键修改点
            for line in open('tools/cub_classnames.txt')
            if line.strip()  # 过滤空行
        ],
        'templates': [
            'a photo of a {}, a type of bird',  # 基础模板
            'a close-up photo of {} in natural habitat',  # 增加场景描述
            'birdwatching observation: {}',      # 专业观察视角
            'zoology illustration of {}',        # 学术插图风格
            'a {} perched on a tree branch',     # 典型行为描述
            'this is an endangered {} bird',     # 强调保护状态
            'taxonomy photo of {} (aves class)', # 学术分类信息
            'wildlife photography of {}',        # 摄影类型说明
            'a juvenile {} learning to fly',     # 生命周期阶段
            'the {} species seen during migration'  # 生态行为
        ]
    },
    "imagenet100": {
        "classes": [
            'tench',
            'goldfish',
            'great white shark',
            'tiger shark',
            'hammerhead shark',
            'electric ray',
            'stingray',
            'rooster',
            'hen',
            'ostrich',
            'brambling',
            'goldfinch',
            'house finch',
            'junco',
            'indigo bunting',
            'American robin',
            'bulbul',
            'jay',
            'magpie',
            'chickadee',
            'American dipper',
            'kite (bird of prey)',
            'bald eagle',
            'vulture',
            'great grey owl',
            'fire salamander',
            'smooth newt',
            'newt',
            'spotted salamander',
            'axolotl',
            'American bullfrog',
            'tree frog',
            'tailed frog',
            'loggerhead sea turtle',
            'leatherback sea turtle',
            'mud turtle',
            'terrapin',
            'box turtle',
            'banded gecko',
            'green iguana',
            'Carolina anole',
            'desert grassland whiptail lizard',
            'agama',
            'frilled-necked lizard',
            'alligator lizard',
            'Gila monster',
            'European green lizard',
            'chameleon',
            'Komodo dragon',
            'Nile crocodile',
            'American alligator',
            'triceratops',
            'worm snake',
            'ring-necked snake',
            'eastern hog-nosed snake',
            'smooth green snake',
            'kingsnake',
            'garter snake',
            'water snake',
            'vine snake',
            'night snake',
            'boa constrictor',
            'African rock python',
            'Indian cobra',
            'green mamba',
            'sea snake',
            'Saharan horned viper',
            'eastern diamondback rattlesnake',
            'sidewinder rattlesnake',
            'trilobite',
            'harvestman',
            'scorpion',
            'yellow garden spider',
            'barn spider',
            'European garden spider',
            'southern black widow',
            'tarantula',
            'wolf spider',
            'tick',
            'centipede',
            'black grouse',
            'ptarmigan',
            'ruffed grouse',
            'prairie grouse',
            'peafowl',
            'quail',
            'partridge',
            'african grey parrot',
            'macaw',
            'sulphur-crested cockatoo',
            'lorikeet',
            'coucal',
            'bee eater',
            'hornbill',
            'hummingbird',
            'jacamar',
            'toucan',
            'duck',
            'red-breasted merganser',
            'goose'
        ],
        "templates": [
            'itap of a {}.',
            'a bad photo of the {}.',
            'a origami {}.',
            'a photo of the large {}.',
            'a {} in a video game.',
            'art of the {}.',
            'a photo of the small {}.',
        ],
    },
}
